---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-cache-iguochan-io-v1-redis
  failurePolicy: Fail
  name: mredis.kb.io
  rules:
  - apiGroups:
    - cache.iguochan.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - redis
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-cache-iguochan-io-v1-redis
  failurePolicy: Fail
  name: vredis.kb.io
  rules:
  - apiGroups:
    - cache.iguochan.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - redis
  sideEffects: None
