apiVersion: cache.iguochan.io/v1
kind: Redis
metadata:
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: redis-sample
    app.kubernetes.io/part-of: redis-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: redis-operator
  name: redis-sample
spec:
  image: redis:7.0
  nodePort: 31000
  storage:
    size: 1Gi
    hostPath: /data
  exporter:
    enable: true
    image: "oliver006/redis_exporter:v1.50.0"
    port: 9121
    resources:
      limits:
        cpu: "100m"
        memory: "128Mi"
      requests:
        cpu: "50m"
        memory: "64Mi"
